name: Run tests

on: 
  push: 
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Instalar dependencias do server
        uses: bahmutov/npm-install@v1
        with:
          working-directory: server
      - name: Instalar dependencias da web
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web
      - name: Tests component & API & UI
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          install: false
          start: npm run start:ci 
          wait-on: 'http://localhost:3000'
        
    
